### ISSUE TITLE
Ability for specify a chunk size based on size not count

### ISSUE THREAD

**Issue by yonderblue** [lanrat/extsort#1]
Currently the chunk size is a count of items implementing SortType, but if SortType also had a Size() it could instead use that, which would be very useful! Otherwise great package! 👍

**Comment by lanrat** [comment]
Hello @yonderblue,

I'm not sure I fully understand what you mean. The Config struct `ChunkSize` field is the number of `SortType` items to group together into a chunk on disk. There are expected to be many chunks, each containing up to `ChunkSize` `SortType` objects in them.

Since `SortType` represents a single sortable item, it would not know how many other items there are to sort, let alone how many should be consolidated into a chunk.

**Comment by yonderblue** [comment]
Hi @lanrat, please see the attached PR.

**Comment by lanrat** [comment]
Closing this issue since the PR is also closed.
